#include "ds3231.h"

/* External handles generated by CubeMX */
extern I2C_HandleTypeDef hi2c1;

int main(void){
    HAL_Init();
    SystemClock_Config();
    MX_I2C1_Init();

    /* Initialize DS3231 with I2C1 and address 0x68 */
    ds3231_init(&hi2c1, 0x68);

    /* ---------------- SET TIME ---------------- */
    RTC_time_t setTime = {
        .seconds = 0,
        .minutes = 45,
        .hours = 10,
        .hour_format = HOUR_FORMAT_12,
        .meridiem = AM    // ignored in 24h mode
    };

    ds3231_setTime(&setTime);


    /* ---------------- CONFIGURE ALARM1 ---------------- */

    RTC_time_t alarmTime = {
        .seconds = 0,
        .minutes = 46,
        .hours = 10,
        .hour_format = HOUR_FORMAT_12,
        .meridiem = AM
    };

    /* Example 1: Trigger When Hours + Minutes + Seconds Match (Every Day) */
    ds3231_setAlarm1Time(&alarmTime);

    /* Match hours + minutes + seconds only (ignore date) */
    ds3231_setAlarm1Mode(DS3231_ALM1_MATCH_SEC_MIN_HRS);

    /* Enable Alarm1 */
    ds3231_enableAlarm1(DS3231_ENABLED);

    /* Clear any previous flag */
    ds3231_clearAlarm1Flag();


    /*Example 2: Trigger When Hours + Minutes + Seconds Match (Every Day) */
    // ds3231_setAlarm1Time(&alarmTime);
    // ds3231_setAlarm1Date(5);   // Day of month
    // ds3231_setAlarm1Mode(DS3231_ALM1_MATCH_SEC_MIN_HRS_DATE);
    // ds3231_enableAlarm1(DS3231_ENABLED);


    /* Example 3: Trigger On Specific Day of Week */
    // ds3231_setAlarm1Time(&alarmTime);
    // ds3231_setAlarm1Day(SUNDAY);
    // ds3231_setAlarm1Mode(DS3231_ALM1_MATCH_SEC_MIN_HRS_DAY);
    // ds3231_enableAlarm1(DS3231_ENABLED);

    /* ---------------- MAIN LOOP ---------------- */

    while (1){
        if (ds3231_isAlarm1Triggered()){
            ds3231_clearAlarm1Flag();

            /* ---- ALARM ACTION ---- */
            /* Toggle LED, send UART message, etc. */
        }

    }
}
