/*
 * Example: DS3231 Square Wave Output
 *
 * Demonstrates:
 *  - Switching INT/SQW pin to square wave mode
 *  - Selecting frequency
 *  - Optional battery-backed square wave
 *
 * Hardware:
 *  - Connect INT/SQW pin to oscilloscope or logic analyzer
 */

#include "ds3231.h"

/* External handle generated by CubeMX */
extern I2C_HandleTypeDef hi2c1;

int main(void){
    HAL_Init();
    SystemClock_Config();
    MX_I2C1_Init();

    /* Initialize DS3231 */
    ds3231_init(&hi2c1, 0x68);

    /* ---- Configure INT/SQW as Square Wave ---- */
    ds3231_setOutputMode(DS3231_OUTPUT_SQUARE_WAVE);

    /* ---- Enable battery-backed square wave (optional) ---- */
    ds3231_setBatteryBackedSquareWave(DS3231_ENABLED);

    /* ---- Select Frequency ---- */
    ds3231_setSquareWaveOutputFreq(DS3231_FREQ_1HZ);
    // Try changing to:
    // DS3231_FREQ_1024Hz
    // DS3231_FREQ_4096Hz
    // DS3231_FREQ_8192Hz

    while (1){
        /* Nothing required in loop
           Frequency is generated in hardware */
    }
}