#include "ds3231.h"

/* External handles generated by CubeMX */
extern I2C_HandleTypeDef hi2c1;

int main(void){
    HAL_Init();
    SystemClock_Config();
    MX_I2C1_Init();

    /* Initialize DS3231 with I2C1 and address 0x68 */
    ds3231_init(&hi2c1, 0x68);

    /* ---------------- SET TIME ---------------- */
    RTC_time_t setTime = {
        .seconds = 0,
        .minutes = 45,
        .hours = 10,
        .hour_format = HOUR_FORMAT_12,
        .meridiem = AM    // ignored in 24h mode
    };

    ds3231_setTime(&setTime);

    /* ---------------- SET DATE ---------------- */
    RTC_date_t setDate = {
        .date  = 21,
        .month = 9,
        .year  = 2025,
        .day   = SUNDAY
    };

    ds3231_setDate(&setDate);

    /* ---------------- MAIN LOOP ---------------- */
    while (1)
    {
        RTC_time_t currentTime;
        RTC_date_t currentDate;
        float temperature;

        /* Read current time */
        ds3231_getTime(&currentTime);

        /* Read current date */
        ds3231_getDate(&currentDate);

        /* Read internal temperature */
        temperature = ds3231_getTemperature();

        /* 
        At this point you can:
        - Print via UART
        - Display on OLED
        - Send over serial
        */

        HAL_Delay(1000);
    }
}