/**
  ******************************************************************************
  * @file    ds18b20_demo.c
  * @brief   DS18B20 demo — reads temperature every 2 seconds and prints
  *          it over a second UART connected to a serial terminal.
  *
  * Hardware setup
  * ──────────────
  *  • USART1  → DS18B20 sensor  (half-duplex, DMA enabled)
  *  • USART2  → USB-to-Serial / ST-Link VCP  (normal TX-only for debug print)
  *
  * Wiring (USART1 pin, e.g. PA9 on STM32F4)
  * ──────────────────────────────────────────
  *   PA9 ──┬── 4.7kΩ ── 3.3V
  *         └── DS18B20 DATA
  *              DS18B20 VCC  → 3.3V
  *              DS18B20 GND  → GND
  *
  * STM32CubeMX settings for USART1
  * ────────────────────────────────
  *  Mode        : Single Wire (Half-Duplex)
  *  Baud rate   : 115200
  *  Word length : 8 bit
  *  Parity      : None
  *  Stop bits   : 1
  *  DMA RX      : DMA2 Stream2, Normal, Peripheral→Memory
  *  DMA TX      : DMA2 Stream7, Normal, Memory→Peripheral
  *  NVIC        : USART1 global interrupt  ✓
  *                DMA2 Stream2 interrupt   ✓
  *                DMA2 Stream7 interrupt   ✓
  ******************************************************************************
  */

#include "main.h"
#include "ds18b20.h"
#include <stdio.h>
#include <string.h>

/* ── Handles generated by CubeMX ─────────────────────────────────────────── */
extern UART_HandleTypeDef huart1;   /* DS18B20 bus  (half-duplex + DMA) */
extern UART_HandleTypeDef huart2;   /* Debug print  (normal mode)       */

/* ── DS18B20 handle ───────────────────────────────────────────────────────── */
DS18B20_HandleTypeDef hds18b20;

/* ── Small helper: send a string over the debug UART ─────────────────────── */
static void debug_print(const char *msg){
    HAL_UART_Transmit(&huart2, (uint8_t *)msg, strlen(msg), 1000);
}

/* ── Application entry point (call from main() after MX_xxx_Init calls) ──── */
void DS18B20_Demo_Run(void){
    char    msg[64];
    float   temperature = 0.0f;

    /* --------------------------------------------------------------------- */
    /* Step 1 — Initialise the library                                        */
    /* --------------------------------------------------------------------- */
    DS18B20_Init(&hds18b20, &huart1, DS18B20_RES_12BIT);
    /*
     * DS18B20_RES_12BIT  → 0.0625 °C resolution, 750 ms conversion time.
     * Change to DS18B20_RES_9BIT for a faster but less precise reading.
     */

    debug_print("DS18B20 demo started\r\n");

    /* --------------------------------------------------------------------- */
    /* Step 2 — (Optional) change resolution and save it to sensor EEPROM     */
    /* --------------------------------------------------------------------- */
    DS18B20_Status_t ret = DS18B20_SetResolution(&hds18b20, DS18B20_RES_12BIT);
    if (ret != DS18B20_OK) {
        debug_print("SetResolution failed — is the sensor connected?\r\n");
        /* Non-fatal: carry on with default resolution */
    }

    /* --------------------------------------------------------------------- */
    /* Step 3 — Main loop: read temperature every 2 seconds                  */
    /* --------------------------------------------------------------------- */
    while (1)
    {
        /*
         * DS18B20_GetTemperature() does three things internally:
         *   1. Sends "start conversion" command
         *   2. Waits the right amount of time for the chosen resolution
         *   3. Reads back and validates the temperature
         */
        ret = DS18B20_GetTemperature(&hds18b20, &temperature);

        switch (ret){
            case DS18B20_OK:
                /* Format and print temperature with 2 decimal places */
                snprintf(msg, sizeof(msg), "Temperature: %.2f C\r\n", temperature);
                debug_print(msg);
                break;

            case DS18B20_ERR_NO_DEVICE:
                debug_print("ERROR: No sensor found. Check wiring & pull-up.\r\n");
                break;

            case DS18B20_ERR_TIMEOUT:
                debug_print("ERROR: UART timeout. Check DMA config & callbacks.\r\n");
                break;

            case DS18B20_ERR_CRC:
                debug_print("ERROR: CRC mismatch. Noisy line or bad connection.\r\n");
                break;

            case DS18B20_ERR_DMA:
                debug_print("ERROR: DMA failure.\r\n");
                break;

            case DS18B20_ERR_RANGE:
                debug_print("ERROR: Temperature out of range (-55 to 125 C).\r\n");
                break;

            default:
                debug_print("ERROR: Unknown error.\r\n");
                break;
        }

        HAL_Delay(2000);   /* Wait 2 seconds before the next reading */
    }
}

/* =========================================================================
 * UART callbacks — MUST be placed in stm32f4xx_it.c or main.c
 *
 * These functions are called automatically by HAL when DMA finishes.
 * The DS18B20 library uses them to know when a byte has been received.
 * Without these, every read will time out and return 0.
 * ========================================================================= */

/**
 * @brief  Called by HAL when a UART DMA receive transfer completes.
 *         Forward to the DS18B20 library so it knows data is ready.
 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    DS18B20_RxCpltCallback(&hds18b20, huart);
}

/**
 * @brief  Called by HAL when a UART error occurs.
 *         Forward to the DS18B20 library so it can abort cleanly.
 */
void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    DS18B20_ErrorCallback(&hds18b20, huart);
}

/* =========================================================================
 * Advanced example — non-blocking usage
 *
 * Use this pattern if you don't want to block for 750 ms during conversion.
 * Instead, start conversion, do other work, then read after enough time.
 * ========================================================================= */
#if 0   /* Change to #if 1 to compile this section */

void DS18B20_NonBlocking_Example(void)
{
    float temperature = 0.0f;
    char  msg[64];

    /* Trigger conversion — returns immediately */
    if (DS18B20_StartConversion(&hds18b20) != DS18B20_OK) {
        debug_print("Conversion start failed\r\n");
        return;
    }

    /*
     * Do other work here while the sensor is measuring...
     * For 12-bit resolution you must wait at least 750 ms total
     * before calling DS18B20_ReadTemperature().
     */
    HAL_Delay(750);   /* Replace with your own non-blocking timer */

    /* Now read the result */
    DS18B20_Status_t ret = DS18B20_ReadTemperature(&hds18b20, &temperature);
    if (ret == DS18B20_OK) {
        snprintf(msg, sizeof(msg), "Non-blocking temp: %.2f C\r\n", temperature);
        debug_print(msg);
    }
}

#endif   /* non-blocking example */